# Generated by Django 3.2.11 on 2023-04-26 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rss_feed",
            fields=[
                ("id", models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=300)),
                (
                    "feed_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("published_datetime", models.DateField()),
                ("link", models.CharField(max_length=1000)),
                ("title", models.TextField()),
                ("title_translation", models.TextField(null=True)),
                (
                    "title_parsed_clean",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "title_parsed_lemma",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "title_parsed_segmented",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "title_parsed_prefixes",
                    models.JSONField(null=True),
                ),
                (
                    "title_parsed_postag",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "title_parsed_feats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "title_parsed_translation_override",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("other_fields", models.JSONField(null=True)),
                ("summary", models.TextField(null=True)),
            ],
        ),
    ]
