# Generated by Django 5.0.1 on 2024-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric_sentence',
            name='translation_azure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lyric_sentence',
            name='translation_google',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rss_sentence',
            name='translation_azure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rss_sentence',
            name='translation_google',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subtitle_sentence',
            name='translation_azure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subtitle_sentence',
            name='translation_google',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wikipedia_sentence',
            name='translation_azure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wikipedia_sentence',
            name='translation_google',
            field=models.TextField(null=True),
        ),
    ]
