# Generated by Django 4.2.1 on 2024-01-21 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Open_subtitles',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Song_habibi',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='episode_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='imdb_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='number_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='people',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='runtime_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='season_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='series_year_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='series_year_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='title_english',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='title_foreign',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
