# Generated by Django 5.0.1 on 2024-06-03 11:18

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_lyric_sentence_translation_azure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_name', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Document_sentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('translation', models.TextField(null=True)),
                ('translation_google', models.TextField(null=True)),
                ('translation_azure', models.TextField(null=True)),
                ('time_translated', models.DateTimeField(null=True)),
                ('sentence_order', models.IntegerField()),
                ('parsed_text', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_clean', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_segmented', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_lemma', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_pos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_features', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_prefixes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_suffixes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_roots', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_gloss_lemma', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('parsed_gloss_flexion', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='articles.user_document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
