# Generated by Django 3.2.11 on 2023-04-26 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import words.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexion',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('translation_google', models.CharField(max_length=300, null=True)),
                ('translation_azure', models.CharField(max_length=300, null=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word_diacritic', models.CharField(max_length=100, null=True)),
                ('translation', models.CharField(max_length=300, null=True)),
                ('root', models.CharField(max_length=100, null=True)),
                ('flexion_counts', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('rank_open_subtitles', models.IntegerField(null=True)),
                ('count_open_subtitles', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=100)),
                ('user_translations', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('user_roots', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordrating',
            constraint=models.UniqueConstraint(fields=('word', 'user'), name='unique_word_user_combination'),
        ),
        migrations.AlterUniqueTogether(
            name='wordrating',
            unique_together={('word', 'user')},
        ),
    ]
