# Generated by Django 4.2.1 on 2024-01-21 10:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import words.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexion',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('translation_google', models.CharField(max_length=300, null=True)),
                ('translation_azure', models.CharField(max_length=300, null=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word_diacritic', models.CharField(max_length=100, null=True)),
                ('translation', models.CharField(max_length=300, null=True)),
                ('root', models.CharField(max_length=100, null=True)),
                ('flexion_counts', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('rank_rss_feed', models.IntegerField(null=True)),
                ('count_rss_feed', models.IntegerField(null=True)),
                ('rank_subtitle', models.IntegerField(null=True)),
                ('count_subtitle', models.IntegerField(null=True)),
                ('count_song', models.IntegerField(null=True)),
                ('rank_song', models.IntegerField(null=True)),
                ('count_wikipedia', models.IntegerField(null=True)),
                ('rank_wikipedia', models.IntegerField(null=True)),
                ('rank_lyric', models.IntegerField(null=True)),
                ('count_lyric', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=100)),
                ('user_translations', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('user_roots', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('parser_translations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('user_translations_with_user', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
                ('user_roots_with_user', models.JSONField(blank=True, default=words.models.default_json_values, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_ratings', to='words.word')),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['text'], name='words_word_text_c757ab_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language'], name='words_word_languag_35ee86_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['rank'], name='words_word_rank_955b91_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['word', 'user'], name='words_wordr_word_id_2bd799_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['word'], name='words_wordr_word_id_d7c995_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['user'], name='words_wordr_user_id_4b3348_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordrating',
            constraint=models.UniqueConstraint(fields=('word', 'user'), name='unique_word_user_combination'),
        ),
        migrations.AlterUniqueTogether(
            name='wordrating',
            unique_together={('word', 'user')},
        ),
    ]
