# Generated by Django 4.0.1 on 2023-04-29 17:20

from django.db import migrations, models
import django.db.models.deletion
import words.models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_roots_with_user',
            field=models.JSONField(blank=True, default=words.models.default_json_values, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='user_translations_with_user',
            field=models.JSONField(blank=True, default=words.models.default_json_values, null=True),
        ),
        migrations.AlterField(
            model_name='wordrating',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_ratings', to='words.word'),
        ),
    ]
