# Generated by Django 3.2.11 on 2023-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['text'], name='words_word_text_c757ab_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['word', 'user'], name='words_wordr_word_id_2bd799_idx'),
        ),
    ]
