# Generated by Django 5.0.1 on 2024-01-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='count_rss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='rank_rss',
            field=models.IntegerField(null=True),
        ),
    ]
