# Generated by Django 5.0.1 on 2024-01-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexion',
            name='translation',
            field=models.TextField(null=True),
        ),
    ]
