# Generated by Django 3.2.11 on 2023-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20230426_1542'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['rank'], name='words_word_rank_955b91_idx'),
        ),
    ]
