# Generated by Django 5.0.1 on 2024-01-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_count_rss_word_rank_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation_azure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='translation_google',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.TextField(null=True),
        ),
    ]
