# Generated by Django 5.0.1 on 2024-01-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_flexion_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexion',
            name='translation',
        ),
    ]
