# Generated by Django 3.2.11 on 2023-04-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_words_word_rank_955b91_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language'], name='words_word_languag_35ee86_idx'),
        ),
    ]
