# Generated by Django 3.2.11 on 2023-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_words_word_languag_35ee86_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['word'], name='words_wordr_word_id_d7c995_idx'),
        ),
        migrations.AddIndex(
            model_name='wordrating',
            index=models.Index(fields=['user'], name='words_wordr_user_id_4b3348_idx'),
        ),
    ]
