# Generated by Django 5.0.1 on 2024-03-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_flexion_parser_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexion',
            name='lemma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='words.word'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='flexion',
            constraint=models.UniqueConstraint(fields=('text', 'lemma', 'language'), name='unique_flexion'),
        ),
    ]
