# Generated by Django 5.0.1 on 2024-03-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_flexion_lemma_flexion_unique_flexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexion',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexions', to='words.word'),
        ),
    ]
