# Generated by Django 5.0.1 on 2024-04-11 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_flexion_lemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
